import Head from "next/head";
import Banner from "../components/Banner";
import Card from "../components/card";
// import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  console.log("HI getStaticProps");

  const options = {
    method: "GET",
    headers: {
      Accept: "application/json",
      Authorization: process.env.FOURSQUARE_AUTH_TOKEN,
    },
  };

  const response = await fetch(
    "https://api.foursquare.com/v3/places/search?query=coffee%20shop&near=belfast&limit=6",
    options
  );

  const data = await response.json();
  console.log("DATA -", data);

  return {
    props: {
      coffeeStores: data.results
    },
  };
}

export default function Home(props) {
  // console.log("PROPS -", props);
  const handleOnBannerClick = () => {
    console.log("Banner button clicked");
  };

  return (
    <div>
      <Head>
        <title>Coffee Shop Locations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner
        buttonText="View stores nearby"
        handleOnClick={handleOnBannerClick}
      />

      {props.coffeeStores.length > 0 && (
        <>
          <h2 className="text-3xl font-bold text-[#DA9A07]">Local Stores</h2>

          <div className="grid grid-cols-1 gap-4 mt-12 sm:grid-cols-2 md:grid-cols-3 pb-12">
            {props.coffeeStores.map((coffeeStore) => {
              return (
                <Card
                  key={coffeeStore.fsq_id}
                  name={coffeeStore.name}
                  imgUrl={
                    coffeeStore.imgUrl ||
                    "https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80"
                  }
                  href={`/coffee-store/` + `${coffeeStore.name}`}
                />
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}
